### ISSUE TITLE
Setting customHandleRequest in a plugin.

### ISSUE THREAD

**Issue by ccollie** [PabloSzx/graphql-ez#214]
Is this possible ? I need to modify the request before parsing.

**Comment by PabloSzx** [comment]
Hi, I just pushed a commit that fixes being able to do it, you can overwrite `customHandleRequest` in `ctx.options` in either `onRegister` or `onAppRegister`, keep in mind that if you want the plugin you be publicly available this should be behind some flag or something, since it would override the default main logic

**Comment by PabloSzx** [comment]
fix already available in the current releases

**Comment by ccollie** [comment]
Nice! For reference, it's for an Apollo compatible `automatic persisted queries`. I want to do it in `envelop` but I don't think it's possible (yet). I raised an issue [here](https://github.com/dotansimha/envelop/issues/581)

**Comment by PabloSzx** [comment]
interesting, it should be possible to make an EZ Plugin that wraps around the request and the envelop plugin

**Comment by ccollie** [comment]
Do you have any ideas of how we can do this so that the `envelop` plugin is still self-contained ? Otherwise I'll do it completely in `graphql-ez`.

**Comment by PabloSzx** [comment]
The current architecture of Envelop won't allow the concept of an empty query and the hash being in "extensions", I'm pretty sure this is a task for graphql-ez, and won't be possible to be a self-contained envelop plugin.

I also could add an extra helper that is called right before "processRequest" and allows for intercepting it. and a plugin for the automatic persisted queries can be made around that
