### ISSUE TITLE
Unify naming of plugin-parameters

### ISSUE THREAD

**Issue by benbender** [PabloSzx/graphql-ez#315]
ATM some of the plugin-parameters are using an URL-suffix, some do not. Some use uppercased "URL", some use camelCased "Url". It would be nice to unify them. Preferably I would like to drop the URL-suffix where no full-url is needed.

Even if it's a minor-detail, I just stumbled upon this inconsistency :)

I can prepare a PR but wanted to ask first as I'm unsure about the handling of BC-concerns at this point in the project.

**Comment by PabloSzx** [comment]
yeah for sure, feel free to create a PR, that's a good suggestion, thank you 👍
