### ISSUE TITLE
Possible GiraphQL-Plugin

### ISSUE THREAD

**Issue by benbender** [PabloSzx/graphql-ez#324]
(Extracted this one into it's own issue as it is separate from the nexus-plugin)

> About GiraphQL I'm completely aware of its existence, just I haven't used it personally, but maybe a convenience plugin just like this one could be useful for GiraphQL as well

Imho the question is where to draw the line about the separation of concerns between GiraphQL and Graphql-ez/Envelop. Both systems have substantial overlapping capabilities and there are much fewer setup-steps compared to nexus.

At the moment I'm doing everything schema-related inside GiraphQL and simply add the resulting executable schema to graphql-ez, which acts basically as an abstraction for the server and a caching-layer.

I'm liking this solution as it's quite flexible and has a clear line of separation. 

What I could think of would be a plugin which would take a GiraphQL-builder-instance instead of the schema and additionally could register given scalars inside the builder. But I have to say that I'm unsure if I would like to use such a plugin as the benefit seems quite minimal to outweight the tighter coupling...

**Comment by RicardoValero95** [comment]
I've been using nexus, but codegen imo is not the best experience. 
I saw this some days ago and I've been enjoying writing my resolvers with giraphql.
It'd be nice an ez with giraphql example, maybe?

**Comment by PabloSzx** [comment]
@RicardoValero95 https://github.com/PabloSzx/graphql-ez/tree/main/examples/fastify/giraphql created this minimal example, with ESM support and using Fastify

**Comment by PabloSzx** [comment]
Following the decision of not having a nexus plugin, this plugin should not be worth the maintainability efforts for too small benefits
