### ISSUE TITLE
SvelteKit & Altair GraphQL Client IDE

### ISSUE THREAD

**Issue by jycouet** [PabloSzx/graphql-ez#629]
I'm on SvelteKit and to try Altair plugin, I created a new file: `./src/routes/api/altair.ts`

With
```js
import { ezUnpkgAltairIDE } from '@graphql-ez/plugin-altair/unpkg';
import { CreateApp } from '@graphql-ez/sveltekit';

const ezAltairApp = CreateApp({
	path: '/api/graphql',
	schema: 'dynamic',
	ez: {
		plugins: [
			ezUnpkgAltairIDE({
				endpoint: '/api/graphql',
				path: '/api/altair'
			})
		]
	}
});

const { handler } = ezAltairApp.buildApp();

export const get = handler;
```

And, when I go to my route, I have in the console:
```cmd
Refused to apply style from 'http://localhost:3178/api/altair/styles.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
altair:25 GET http://localhost:3178/api/altair/assets/img/logo_350.svg 404 (Not Found)
altair:35 GET http://localhost:3178/api/altair/runtime-es2018.js net::ERR_ABORTED 404 (Not Found)
altair:36 GET http://localhost:3178/api/altair/polyfills-es2018.js net::ERR_ABORTED 404 (Not Found)
altair:37 GET http://localhost:3178/api/altair/main-es2018.js net::ERR_ABORTED 404 (Not Found)
altair:39 Uncaught ReferenceError: AltairGraphQL is not defined
    at altair:39
(anonymous) @ altair:39
favicon.ico:1 GET http://localhost:3178/api/altair/favicon.ico 404 (Not Found)
```

I tried the different versions explained in the doc but none worked. 
I guess that in sveltekit something need to be tweaked to make it work.

If you could guide me, I'm interested to see this Altair.

For info, I have a graphiQL working like a charme on `./src/routes/api/graphiql.ts`
For info2, I like a lot Ez 👌

**Comment by PabloSzx** [comment]
In the example of sveltekit altair is working perfectly, for altair is needed a wildcard / fallthrough route

check https://github.com/PabloSzx/graphql-ez/tree/main/examples/sveltekit

**Comment by jycouet** [comment]
A **wildcard / fallthrough route**, perfect!!! thx a lot for the hint.
Puting the code in `./api/[...any].ts` did the job.


For info, with `import { ezUnpkgAltairIDE } from '@graphql-ez/plugin-altair/unpkg';` I get a lot of timeout (might be also my connexion 🤷‍♂️) So I don't use the **Unpkg** and it's working well.
 

 For others, here is my `./api/[...any].ts` that is working well:
```js
import { ezAltairIDE } from '@graphql-ez/plugin-altair';
import { ezGraphiQLIDE } from '@graphql-ez/plugin-graphiql';
import { ezVoyager } from '@graphql-ez/plugin-voyager';
import { CreateApp } from '@graphql-ez/sveltekit';

const ezApp = CreateApp({
	path: '/api/graphql',
	schema: 'dynamic',
	ez: {
		plugins: [
			ezAltairIDE({
				path: '/api/altair',
				instanceStorageNamespace: 'sveltekit'
			}),
			ezGraphiQLIDE({
				path: '/api/graphiql'
			}),
			ezVoyager({
				path: '/api/voyager'
			})
		]
	}
});

const { handler } = ezApp.buildApp();

export const get = handler;

export const post = handler;
```

@PabloSzx do you want me to PR the doc to add the info?

**Comment by jycouet** [comment]
Thx @PabloSzx for the additional info.

I was looking at the plugin doc: https://www.graphql-ez.com/plugins/altair 
sveltekit doc is well done 👍

Thank you for everything

**Comment by PabloSzx** [comment]
Oh yeah, the altair plugins docs have specific usage instructions for cloudflare, next and vercel but not sveltekit, I will add quick instructions 👍
