### ISSUE TITLE
SvelteKit & GraphQL Modules

### ISSUE THREAD

**Issue by jycouet** [PabloSzx/graphql-ez#630]
I'm on SvelteKit and to try GraphQL Modules plugin _(I'm using the envelop version)_

As soon as I add `@Injectable({ global: true, scope: Scope.Operation })` on top of my provider class, SvelteKit tell me that he can't handle this.
```cmd error
[vite] Error when evaluating SSR module
```

In the end, I found that building the context on Ez side is very nice (and typed) so I will not use this way of providers. But if it's not working maybe it should be written in the doc as a limitation? (I could PR the doc if you want)
▶ I'm maybe wrong, and it should work. let me know.

I use mainly GraphQL Modules to organize well my code, and I have a pretty good result. 
I will record a video to explain a bit the idea, hope you will like it 🤞.
I have a few ideas to enhance [`modules / dataloader / Context Type`], and I'm sure that we can make it happen 😎

**Comment by PabloSzx** [comment]
Sveltekit doesn't use tsc for the transpillation, it uses esbuild, and esbuild doesn't have 1-to-1 decorators equivalent as tsc, that requires type-reflection, which no other than tsc has

https://github.com/evanw/esbuild/issues/257

https://github.com/evanw/esbuild/issues/257

https://github.com/sveltejs/kit/issues/798

**Comment by jycouet** [comment]
Thank you @PabloSzx for this detail 👍
And great work.
